<?php
$name = 'Add new cat';
$this->headTitle($name);
?>
<h1><?= $this->escapeHtml($c) ?></h1>
<?php
$cat = $form->get('name');
$cat->setAttribute('class', 'form-control');
$cat->setAttribute('placeholder', 'Cat name');

$race = $form->get('race');
$race->setAttribute('class', 'form-control');
$race->setAttribute('placeholder', 'Race');

$photo = $form->get('photo_url');
$photo->setAttribute('class', 'form-control');
$photo->setAttribute('placeholder', 'Photo URL');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('cat', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($cat) ?>
    <?= $this->formElement($cat) ?>
    <?= $this->formElementErrors()->render($cat, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($race) ?>
    <?= $this->formElement($race) ?>
    <?= $this->formElementErrors()->render($race, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($photo) ?>
    <?= $this->formElement($photo) ?>
    <?= $this->formElementErrors()->render($photo, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('owner_id'));
echo $this->form()->closeTag();