<?php
// module/Cat/view/cat/cat/edit.phtml:

$title = 'Edit cat';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$cat = $form->get('name');
$cat->setAttribute('class', 'form-control');
$cat->setAttribute('placeholder', 'Cat name');

$race = $form->get('race');
$race->setAttribute('class', 'form-control');
$race->setAttribute('placeholder', 'Race');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('cat', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($cat) ?>
    <?= $this->formElement($cat) ?>
    <?= $this->formElementErrors()->render($cat, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($race) ?>
    <?= $this->formElement($race) ?>
    <?= $this->formElementErrors()->render($race, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('owner_id'));
echo $this->form()->closeTag();