<?php
$title = 'Kitty Cats';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<table class="table">
<tr>
    <th>Image</th>
    <th>Name</th>
    <th>Race</th>
    <th>Owner</th>
</tr>
<?php foreach ($cats as $cat) : ?>
    <tr>
        <td><img src="<?= $this->escapeHtml($cat->photoUrl??'https://cataas.com/cat') ?>" alt="<?= $cat->name ?>" width="100" height="100"/></td>
        <td><?= $this->escapeHtml($cat->name) ?></td>
        <td><?= $this->escapeHtml($cat->race) ?></td>
        <td><?= $this->escapeHtml($cat->ownerName) ?></td>
    </tr>
<?php endforeach; ?>
</table>